#pragma once

#include <iostream>
#include <string>
#include <filesystem>
#include <format>

#include <File.hpp>
#include <FileHeader.hpp>
#include <FileSource.hpp>

#include <DataType.hpp>
#include <DataTypeChar.hpp>
#include <DataTypeDouble.hpp>
#include <DataTypeFloat.hpp>
#include <DataTypeInt.hpp>
#include <DataTypeLong.hpp>
#include <DataTypeLongDouble.hpp>
#include <DataTypeLongInt.hpp>
#include <DataTypeLongLong.hpp>
#include <DataTypeLongLongInt.hpp>
#include <DataTypeShort.hpp>
#include <DataTypeShortInt.hpp>
#include <DataTypeSigned.hpp>
#include <DataTypeSignedChar.hpp>
#include <DataTypeSignedInt.hpp>
#include <DataTypeSignedLong.hpp>
#include <DataTypeSignedLongInt.hpp>
#include <DataTypeSignedLongLong.hpp>
#include <DataTypeSignedLongLongInt.hpp>
#include <DataTypeSignedShort.hpp>
#include <DataTypeSignedShortInt.hpp>
#include <DataTypeUnsigned.hpp>
#include <DataTypeUnsignedChar.hpp>
#include <DataTypeUnsignedInt.hpp>
#include <DataTypeUnsignedLong.hpp>
#include <DataTypeUnsignedLongInt.hpp>
#include <DataTypeUnsignedLongLong.hpp>
#include <DataTypeUnsignedLongLongInt.hpp>
#include <DataTypeUnsignedShort.hpp>
#include <DataTypeUnsignedShortInt.hpp>
