set(FILEHEADER_ROOT
  ${CMAKE_SOURCE_DIR}/src/${PROMETHEUS_LANG}/File/FileHeader
)

file(GLOB FILEHEADER_SOURCES_PUBLIC_TEMP
  ${FILEHEADER_ROOT}/public/src/*.cpp
)

file(GLOB FILEHEADER_HEADERS_PUBLIC_TEMP
  ${FILEHEADER_ROOT}/public/include/*.hpp
)

set(FILEHEADER_SOURCES
  ${FILEHEADER_SOURCES_PUBLIC_TEMP}
  PARENT_SCOPE
)

set(FILEHEADER_HEADERS
  ${FILEHEADER_HEADERS_PUBLIC_TEMP}
  PARENT_SCOPE
)

set(FILEHEADER_INCLUDEDIR_PUBLIC
  ${FILEHEADER_ROOT}/public/include
  PARENT_SCOPE
)


