set(FILESOURCE_ROOT
  ${CMAKE_SOURCE_DIR}/src/${PROMETHEUS_LANG}/File/FileSource
)

file(GLOB FILESOURCE_SOURCES_PUBLIC_TEMP
  ${FILESOURCE_ROOT}/public/src/*.cpp
)

file(GLOB FILESOURCE_HEADERS_PUBLIC_TEMP
  ${FILESOURCE_ROOT}/public/include/*.hpp
)

set(FILESOURCE_SOURCES
  ${FILESOURCE_SOURCES_PUBLIC_TEMP}
  PARENT_SCOPE
)

set(FILESOURCE_HEADERS
  ${FILESOURCE_HEADERS_PUBLIC_TEMP}
  PARENT_SCOPE
)

set(FILESOURCE_INCLUDEDIR_PUBLIC
  ${FILESOURCE_ROOT}/public/include
  PARENT_SCOPE
)

